// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// gibbs_sf
Rcpp::List gibbs_sf(const arma::vec& y, const arma::mat& X, const arma::uvec& g, const int n_units, const arma::vec& b0, const arma::mat& B0i, const double a_v, const double b_v, const double a_u, const double b_u, const arma::vec& beta_init, const double sigma_v2_init, const double par_u_init, const arma::vec& u_init, const int ineff, const double s, const int draws, const int burnin, const int thin, const bool keep_u, const int verbose);
RcppExport SEXP _bsfa_gibbs_sf(SEXP ySEXP, SEXP XSEXP, SEXP gSEXP, SEXP n_unitsSEXP, SEXP b0SEXP, SEXP B0iSEXP, SEXP a_vSEXP, SEXP b_vSEXP, SEXP a_uSEXP, SEXP b_uSEXP, SEXP beta_initSEXP, SEXP sigma_v2_initSEXP, SEXP par_u_initSEXP, SEXP u_initSEXP, SEXP ineffSEXP, SEXP sSEXP, SEXP drawsSEXP, SEXP burninSEXP, SEXP thinSEXP, SEXP keep_uSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type g(gSEXP);
    Rcpp::traits::input_parameter< const int >::type n_units(n_unitsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type b0(b0SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type B0i(B0iSEXP);
    Rcpp::traits::input_parameter< const double >::type a_v(a_vSEXP);
    Rcpp::traits::input_parameter< const double >::type b_v(b_vSEXP);
    Rcpp::traits::input_parameter< const double >::type a_u(a_uSEXP);
    Rcpp::traits::input_parameter< const double >::type b_u(b_uSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type beta_init(beta_initSEXP);
    Rcpp::traits::input_parameter< const double >::type sigma_v2_init(sigma_v2_initSEXP);
    Rcpp::traits::input_parameter< const double >::type par_u_init(par_u_initSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type u_init(u_initSEXP);
    Rcpp::traits::input_parameter< const int >::type ineff(ineffSEXP);
    Rcpp::traits::input_parameter< const double >::type s(sSEXP);
    Rcpp::traits::input_parameter< const int >::type draws(drawsSEXP);
    Rcpp::traits::input_parameter< const int >::type burnin(burninSEXP);
    Rcpp::traits::input_parameter< const int >::type thin(thinSEXP);
    Rcpp::traits::input_parameter< const bool >::type keep_u(keep_uSEXP);
    Rcpp::traits::input_parameter< const int >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(gibbs_sf(y, X, g, n_units, b0, B0i, a_v, b_v, a_u, b_u, beta_init, sigma_v2_init, par_u_init, u_init, ineff, s, draws, burnin, thin, keep_u, verbose));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_bsfa_gibbs_sf", (DL_FUNC) &_bsfa_gibbs_sf, 21},
    {NULL, NULL, 0}
};

RcppExport void R_init_bsfa(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
