// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// gibbs_sf
Rcpp::List gibbs_sf(const arma::vec& y, const arma::mat& X, const arma::uvec& g, const int n_units, const arma::vec& b0, const arma::mat& B0i, const arma::uvec& ssvs_idx, const arma::vec& tau0, const arma::vec& tau1, const arma::vec& prob_prior, const int varsel, const double a_v, const double b_v, const double a_u, const double b_u, const arma::vec& beta_init, const double sigma_v2_init, const double par_u_init, const arma::vec& u_init, const int ineff, const double s, const int draws, const int burnin, const int thin, const int u_thin, const int verbose);
RcppExport SEXP _bsfa_gibbs_sf(SEXP ySEXP, SEXP XSEXP, SEXP gSEXP, SEXP n_unitsSEXP, SEXP b0SEXP, SEXP B0iSEXP, SEXP ssvs_idxSEXP, SEXP tau0SEXP, SEXP tau1SEXP, SEXP prob_priorSEXP, SEXP varselSEXP, SEXP a_vSEXP, SEXP b_vSEXP, SEXP a_uSEXP, SEXP b_uSEXP, SEXP beta_initSEXP, SEXP sigma_v2_initSEXP, SEXP par_u_initSEXP, SEXP u_initSEXP, SEXP ineffSEXP, SEXP sSEXP, SEXP drawsSEXP, SEXP burninSEXP, SEXP thinSEXP, SEXP u_thinSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type g(gSEXP);
    Rcpp::traits::input_parameter< const int >::type n_units(n_unitsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type b0(b0SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type B0i(B0iSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type ssvs_idx(ssvs_idxSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type tau0(tau0SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type tau1(tau1SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type prob_prior(prob_priorSEXP);
    Rcpp::traits::input_parameter< const int >::type varsel(varselSEXP);
    Rcpp::traits::input_parameter< const double >::type a_v(a_vSEXP);
    Rcpp::traits::input_parameter< const double >::type b_v(b_vSEXP);
    Rcpp::traits::input_parameter< const double >::type a_u(a_uSEXP);
    Rcpp::traits::input_parameter< const double >::type b_u(b_uSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type beta_init(beta_initSEXP);
    Rcpp::traits::input_parameter< const double >::type sigma_v2_init(sigma_v2_initSEXP);
    Rcpp::traits::input_parameter< const double >::type par_u_init(par_u_initSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type u_init(u_initSEXP);
    Rcpp::traits::input_parameter< const int >::type ineff(ineffSEXP);
    Rcpp::traits::input_parameter< const double >::type s(sSEXP);
    Rcpp::traits::input_parameter< const int >::type draws(drawsSEXP);
    Rcpp::traits::input_parameter< const int >::type burnin(burninSEXP);
    Rcpp::traits::input_parameter< const int >::type thin(thinSEXP);
    Rcpp::traits::input_parameter< const int >::type u_thin(u_thinSEXP);
    Rcpp::traits::input_parameter< const int >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(gibbs_sf(y, X, g, n_units, b0, B0i, ssvs_idx, tau0, tau1, prob_prior, varsel, a_v, b_v, a_u, b_u, beta_init, sigma_v2_init, par_u_init, u_init, ineff, s, draws, burnin, thin, u_thin, verbose));
    return rcpp_result_gen;
END_RCPP
}
// gibbs_sf4
Rcpp::List gibbs_sf4(const arma::vec& y, const arma::mat& X, const arma::uvec& g, const int n_units, const arma::vec& b0, const arma::mat& B0i, const arma::uvec& ssvs_idx, const arma::vec& tau0, const arma::vec& tau1, const arma::vec& prob_prior, const int varsel, const double a_v, const double b_v, const double a_mu, const double b_mu, const double a_eta, const double b_eta, const double a_u, const double b_u, const arma::vec& beta_init, const double sigma_v2_init, const double sigma_mu2_init, const double par_eta_init, const double par_u_init, const arma::vec& mu_init, const arma::vec& eta_init, const arma::vec& u_init, const int ineff, const double s, const int draws, const int burnin, const int thin, const int u_thin, const int verbose);
RcppExport SEXP _bsfa_gibbs_sf4(SEXP ySEXP, SEXP XSEXP, SEXP gSEXP, SEXP n_unitsSEXP, SEXP b0SEXP, SEXP B0iSEXP, SEXP ssvs_idxSEXP, SEXP tau0SEXP, SEXP tau1SEXP, SEXP prob_priorSEXP, SEXP varselSEXP, SEXP a_vSEXP, SEXP b_vSEXP, SEXP a_muSEXP, SEXP b_muSEXP, SEXP a_etaSEXP, SEXP b_etaSEXP, SEXP a_uSEXP, SEXP b_uSEXP, SEXP beta_initSEXP, SEXP sigma_v2_initSEXP, SEXP sigma_mu2_initSEXP, SEXP par_eta_initSEXP, SEXP par_u_initSEXP, SEXP mu_initSEXP, SEXP eta_initSEXP, SEXP u_initSEXP, SEXP ineffSEXP, SEXP sSEXP, SEXP drawsSEXP, SEXP burninSEXP, SEXP thinSEXP, SEXP u_thinSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type g(gSEXP);
    Rcpp::traits::input_parameter< const int >::type n_units(n_unitsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type b0(b0SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type B0i(B0iSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type ssvs_idx(ssvs_idxSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type tau0(tau0SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type tau1(tau1SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type prob_prior(prob_priorSEXP);
    Rcpp::traits::input_parameter< const int >::type varsel(varselSEXP);
    Rcpp::traits::input_parameter< const double >::type a_v(a_vSEXP);
    Rcpp::traits::input_parameter< const double >::type b_v(b_vSEXP);
    Rcpp::traits::input_parameter< const double >::type a_mu(a_muSEXP);
    Rcpp::traits::input_parameter< const double >::type b_mu(b_muSEXP);
    Rcpp::traits::input_parameter< const double >::type a_eta(a_etaSEXP);
    Rcpp::traits::input_parameter< const double >::type b_eta(b_etaSEXP);
    Rcpp::traits::input_parameter< const double >::type a_u(a_uSEXP);
    Rcpp::traits::input_parameter< const double >::type b_u(b_uSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type beta_init(beta_initSEXP);
    Rcpp::traits::input_parameter< const double >::type sigma_v2_init(sigma_v2_initSEXP);
    Rcpp::traits::input_parameter< const double >::type sigma_mu2_init(sigma_mu2_initSEXP);
    Rcpp::traits::input_parameter< const double >::type par_eta_init(par_eta_initSEXP);
    Rcpp::traits::input_parameter< const double >::type par_u_init(par_u_initSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type mu_init(mu_initSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type eta_init(eta_initSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type u_init(u_initSEXP);
    Rcpp::traits::input_parameter< const int >::type ineff(ineffSEXP);
    Rcpp::traits::input_parameter< const double >::type s(sSEXP);
    Rcpp::traits::input_parameter< const int >::type draws(drawsSEXP);
    Rcpp::traits::input_parameter< const int >::type burnin(burninSEXP);
    Rcpp::traits::input_parameter< const int >::type thin(thinSEXP);
    Rcpp::traits::input_parameter< const int >::type u_thin(u_thinSEXP);
    Rcpp::traits::input_parameter< const int >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(gibbs_sf4(y, X, g, n_units, b0, B0i, ssvs_idx, tau0, tau1, prob_prior, varsel, a_v, b_v, a_mu, b_mu, a_eta, b_eta, a_u, b_u, beta_init, sigma_v2_init, sigma_mu2_init, par_eta_init, par_u_init, mu_init, eta_init, u_init, ineff, s, draws, burnin, thin, u_thin, verbose));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_bsfa_gibbs_sf", (DL_FUNC) &_bsfa_gibbs_sf, 26},
    {"_bsfa_gibbs_sf4", (DL_FUNC) &_bsfa_gibbs_sf4, 34},
    {NULL, NULL, 0}
};

RcppExport void R_init_bsfa(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
