# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Gibbs sampler for the stochastic frontier model
#'
#' Workhorse behind \code{\link{add_posterior_coefficients}}. Not intended to
#' be called directly, since it performs no input checking.
#'
#' @param y vector of observations on the dependent variable.
#' @param X matrix of regressors.
#' @param g zero-based integer vector mapping each observation to the unit that
#'   owns its inefficiency term.
#' @param n_units number of distinct units in \code{g}.
#' @param b0 prior mean of the frontier coefficients.
#' @param B0i prior precision matrix of the frontier coefficients.
#' @param ssvs_idx zero-based positions of the coefficients placed under
#'   stochastic search variable selection; empty for no variable selection.
#' @param tau0 prior standard deviations of those coefficients when they are
#'   excluded from the frontier.
#' @param tau1 prior standard deviations of those coefficients when they are
#'   included.
#' @param prob_prior prior inclusion probabilities of those coefficients.
#' @param varsel 0 for no variable selection, 1 for stochastic search variable
#'   selection and 2 for the Bayesian variable selection of Korobilis (2013).
#' @param a_v shape of the gamma prior on the error precision.
#' @param b_v rate of the gamma prior on the error precision.
#' @param a_u shape of the gamma prior on the inefficiency parameter.
#' @param b_u rate of the gamma prior on the inefficiency parameter. For
#'   \code{ineff = 0} these refer to the precision of the half-normal
#'   distribution, for \code{ineff = 1} to the exponential rate.
#' @param beta_init starting values of the frontier coefficients.
#' @param sigma_v2_init starting value of the error variance.
#' @param par_u_init starting value of the inefficiency parameter, the scale
#'   for \code{ineff = 0} and the rate for \code{ineff = 1}.
#' @param u_init starting values of the inefficiency terms.
#' @param ineff 0 for half-normal, 1 for exponential inefficiency.
#' @param s -1 for a production frontier, 1 for a cost frontier.
#' @param draws number of retained iterations before thinning.
#' @param burnin number of discarded iterations.
#' @param thin thinning interval.
#' @param u_thin 0 not to store the augmented inefficiency draws, otherwise
#'   the interval at which the retained draws are stored.
#' @param verbose how often to report progress; 0 for no reporting.
#'
#' @return A named list of draw matrices.
#'
#' @keywords internal
gibbs_sf <- function(y, X, g, n_units, b0, B0i, ssvs_idx, tau0, tau1, prob_prior, varsel, a_v, b_v, a_u, b_u, beta_init, sigma_v2_init, par_u_init, u_init, ineff, s, draws, burnin, thin, u_thin, verbose) {
    .Call(`_bsfa_gibbs_sf`, y, X, g, n_units, b0, B0i, ssvs_idx, tau0, tau1, prob_prior, varsel, a_v, b_v, a_u, b_u, beta_init, sigma_v2_init, par_u_init, u_init, ineff, s, draws, burnin, thin, u_thin, verbose)
}

#' Gibbs sampler for the four-component stochastic frontier model
#'
#' Workhorse behind \code{\link{add_posterior_coefficients}} for objects of
#' class \code{"sfmodel4_exp"} and \code{"sfmodel4_hn"}. Not intended to be
#' called directly, since it performs no input checking.
#'
#' @param y vector of observations on the dependent variable.
#' @param X matrix of regressors.
#' @param g zero-based integer vector mapping each observation to its unit.
#' @param n_units number of distinct units in \code{g}.
#' @param b0 prior mean of the frontier coefficients.
#' @param B0i prior precision matrix of the frontier coefficients.
#' @param ssvs_idx zero-based positions of the coefficients placed under
#'   stochastic search variable selection; empty for no variable selection.
#' @param tau0 prior standard deviations of those coefficients when they are
#'   excluded from the frontier.
#' @param tau1 prior standard deviations of those coefficients when they are
#'   included.
#' @param prob_prior prior inclusion probabilities of those coefficients.
#' @param varsel 0 for no variable selection, 1 for stochastic search variable
#'   selection and 2 for the Bayesian variable selection of Korobilis (2013).
#' @param a_v shape of the gamma prior on the error precision.
#' @param b_v rate of the gamma prior on the error precision.
#' @param a_mu shape of the gamma prior on the precision of the unit effect.
#' @param b_mu rate of the gamma prior on the precision of the unit effect.
#' @param a_eta shape of the gamma prior on the persistent inefficiency
#'   parameter.
#' @param b_eta rate of the gamma prior on the persistent inefficiency
#'   parameter.
#' @param a_u shape of the gamma prior on the transient inefficiency
#'   parameter.
#' @param b_u rate of the gamma prior on the transient inefficiency parameter.
#' @param beta_init starting values of the frontier coefficients.
#' @param sigma_v2_init starting value of the error variance.
#' @param sigma_mu2_init starting value of the variance of the unit effect.
#' @param par_eta_init starting value of the persistent inefficiency
#'   parameter.
#' @param par_u_init starting value of the transient inefficiency parameter.
#' @param mu_init starting values of the unit effects.
#' @param eta_init starting values of the persistent inefficiency terms.
#' @param u_init starting values of the transient inefficiency terms.
#' @param ineff 0 for half-normal, 1 for exponential inefficiency.
#' @param s -1 for a production frontier, 1 for a cost frontier.
#' @param draws number of retained iterations before thinning.
#' @param burnin number of discarded iterations.
#' @param thin thinning interval.
#' @param u_thin 0 not to store the augmented terms, otherwise the interval at
#'   which the retained draws are stored.
#' @param verbose how often to report progress; 0 for no reporting.
#'
#' @return A named list of draw matrices.
#'
#' @keywords internal
gibbs_sf4 <- function(y, X, g, n_units, b0, B0i, ssvs_idx, tau0, tau1, prob_prior, varsel, a_v, b_v, a_mu, b_mu, a_eta, b_eta, a_u, b_u, beta_init, sigma_v2_init, sigma_mu2_init, par_eta_init, par_u_init, mu_init, eta_init, u_init, ineff, s, draws, burnin, thin, u_thin, verbose) {
    .Call(`_bsfa_gibbs_sf4`, y, X, g, n_units, b0, B0i, ssvs_idx, tau0, tau1, prob_prior, varsel, a_v, b_v, a_mu, b_mu, a_eta, b_eta, a_u, b_u, beta_init, sigma_v2_init, sigma_mu2_init, par_eta_init, par_u_init, mu_init, eta_init, u_init, ineff, s, draws, burnin, thin, u_thin, verbose)
}

