# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Gibbs sampler for the stochastic frontier model
#'
#' Workhorse behind \code{\link{bsfa}}. Not intended to be called directly,
#' since it performs no input checking.
#'
#' @param y vector of observations on the dependent variable.
#' @param X matrix of regressors.
#' @param g zero-based integer vector mapping each observation to the unit that
#'   owns its inefficiency term.
#' @param n_units number of distinct units in \code{g}.
#' @param b0 prior mean of the frontier coefficients.
#' @param B0i prior precision matrix of the frontier coefficients.
#' @param a_v shape of the gamma prior on the error precision.
#' @param b_v rate of the gamma prior on the error precision.
#' @param a_u shape of the gamma prior on the inefficiency parameter.
#' @param b_u rate of the gamma prior on the inefficiency parameter. For
#'   \code{ineff = 0} these refer to the precision of the half-normal
#'   distribution, for \code{ineff = 1} to the exponential rate.
#' @param beta_init starting values of the frontier coefficients.
#' @param sigma_v2_init starting value of the error variance.
#' @param par_u_init starting value of the inefficiency parameter, the scale
#'   for \code{ineff = 0} and the rate for \code{ineff = 1}.
#' @param u_init starting values of the inefficiency terms.
#' @param ineff 0 for half-normal, 1 for exponential inefficiency.
#' @param s -1 for a production frontier, 1 for a cost frontier.
#' @param draws number of retained iterations before thinning.
#' @param burnin number of discarded iterations.
#' @param thin thinning interval.
#' @param keep_u whether to store the augmented inefficiency draws.
#' @param keep_ll whether to store pointwise log-likelihood contributions.
#' @param verbose how often to report progress; 0 for no reporting.
#'
#' @return A named list of draw matrices.
#'
#' @keywords internal
gibbs_sf <- function(y, X, g, n_units, b0, B0i, a_v, b_v, a_u, b_u, beta_init, sigma_v2_init, par_u_init, u_init, ineff, s, draws, burnin, thin, keep_u, keep_ll, verbose) {
    .Call(`_bsfa_gibbs_sf`, y, X, g, n_units, b0, B0i, a_v, b_v, a_u, b_u, beta_init, sigma_v2_init, par_u_init, u_init, ineff, s, draws, burnin, thin, keep_u, keep_ll, verbose)
}

